### ISSUE TITLE
Too long prompts make ONNX fail

### ISSUE THREAD

**Issue by kungfooman** [dakenf/diffusers.js#21]
Example prompt:

`Beautiful gothic style house in an Italian village, Beautiful gothic style house in an Italian village, Beautiful gothic style house in an Italian village, Beautiful gothic style house in an Italian village, Beautiful gothic style house in an Italian village, Beautiful gothic style house in an Italian village, Beautiful gothic style house in an Italian village, , Beautiful gothic style house in an Italian village, Beautiful gothic style house in an Italian village, Beautiful gothic style house in an Italian village, Beautiful gothic style house in an Italian village, Beautiful gothic style house in an Italian village, Beautiful gothic style house in an Italian village`

Error:

```
wasm-utils.ts:61 Uncaught (in promise) 
Error: failed to call OrtRun(). ERROR_CODE: 1, ERROR_MESSAGE: Non-zero status code returned while running Add node. Name:'/text_model/embeddings/Add' Status Message: Failed to run JSEP kernel
    at t.checkLastError (wasm-utils.ts:61:11)
    at t.run (wasm-core-impl.ts:313:9)
    at async t.OnnxruntimeWebAssemblySessionHandler.run (session-handler.ts:120:11)
    at async a.run (inference-session-impl.js:94:15)
    at async e.run (index.esm.js:352:12)
    at async e.encodePrompt (index.esm.js:1014:5)
    at async e.run (index.esm.js:1497:11)
    at async onClick (App.js:217:11)
```

@dakenf What are you up to lately? Last commit is quite some time ago. This project is amazing, you could add a donation option, if you run out of resources.

**Comment by kungfooman** [comment]
Fixed by https://github.com/dakenf/diffusers.js/pull/19

Thank you @jdp8 for working this out and @dakenf for merging 🥇
