### ISSUE TITLE
Model rename and Model load issue

### ISSUE THREAD

**Issue by technic404** [dakenf/diffusers.js#6]
When firstly executed `node index.mjs` with the sample code for node.js, provided error occurs:
```js
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, rename 'F:\Programming\.cache\aislamov\stable-diffusion-2-1-base-onnx\model_index.json.tmp' -> ''F:\Programming\.cache\aislamov\stable-diffusion-2-1-base-onnx\model_index.json'] {                                                -> 
  errno: -4058,
  code: 'ENOENT',
  syscall: 'rename',
  path: ''F:\Programming\\.cache\\aislamov\\stable-diffusion-2-1-base-onnx\\model_index.json.tmp',
  dest: ''F:\Programming\\.cache\\aislamov\\stable-diffusion-2-1-base-onnx\\model_index.json'
}
```

When I run that secondly, another error occurs:
```js
Downloading model_index.json | ████████████████████████████████████████ | 100% | 587 Bytes/587 Bytes
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getModelJSON (file:///F:/Programming/node_modules/@aislamov/diffusers.js/dist/index-node.esm.js:109:15)
    at async DiffusionPipeline.fromPretrained (file:///F:/Programming/node_modules/@aislamov/diffusers.js/dist/index-node.esm.js:1178:19)

Node.js v18.15.0
```

I think here is similar error to that first one - `model_index.json.tmp` should be renamed to `model_index.json`, so then the *Unexpected end of JSON input* won't occur anymore.

Last error i got is:
```js
F:\Programming\node_modules\onnxruntime-node\dist\backend.js:24
            __classPrivateFieldGet(this, _OnnxruntimeSessionHandler_inferenceSession, "f").loadModel(pathOrBuffer, options);
                                                                                           ^

Error: Failed to find kernel for BiasSplitGelu(1) (node BiasSplitGelu_0). Kernel not found
    at new OnnxruntimeSessionHandler (F:\Programming\node_modules\onnxruntime-node\dist\backend.js:24:92)
    at F:\Programming\node_modules\onnxruntime-node\dist\backend.js:64:29
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.15.0
```

**Comment by dakenf** [comment]
Thanks for the feedback, i will fix the rename issue in the next release. As you use node.js with CPU, you need to add `--rev cpu` to command line when running node example. That way it will download a special model version without GPU-specific optimizations

CUDA/DML providers for node.js are not yet released by ONNX team (my PR for that was already merged https://github.com/microsoft/onnxruntime/pull/16050 )
